spring.application.name=springboot_demo
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:2006/spring
spring.datasource.username=postgres
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update
